name: SiriLog
main: sirilog.Main
version: 0.0.5
commands:
   sl:
      description: Shows SiriLog's version.
      usage: /sl
      permission: sirilog.info
      permission-message: You don't have permission to use SiriLog's info command.